name: Download Bing Daily Image

on:
  schedule:
    - cron: "30 4 * * *"

jobs:
  download_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Bing daily image
        run: |
          mkdir -p assets
          curl -o assets/background.jpg https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US | grep -oP '(?<="url":")[^"]+' | sed 's/^/https:\/\/www.bing.com/' | xargs curl -o assets/background.jpg

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/background.jpg
          git commit -m "Update background image"
